version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/app
    ports:
      - "9003:9000"
  nginx:
    image: nginx:stable
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf