when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

index:
    path: /users
    controller: MiniApi\Controller\ApiController::users
